In [1]:
!python3 --version

Python 3.10.11

In [2]:
# Ejecutar si se trabaja en maquina local
MAIN_ROUTE = '..'

In [3]:
import pandas as pd

df = pd.read_csv(MAIN_ROUTE+"/data/processed/productos_corpus.csv",delimiter=",")

len(df)

46490

In [4]:
df

,SKU,DESCRIPCION,DES_DIV,DES_AREA,DES_DPTO,DES_LIN,DES_MARCA,DES_PROCE,URL,CHUNK_PRODUCTO,CHUNK_FICHA,CHUNK_DESCRIPCION,CHUNK_CARACTERISTICAS,CHUNK_OBSERVACIONES,CHUNK_RECOMENDACIONES
0,10236,OVALIN CIRCULAR P/SOBREP ORANGE VIDRIOTRANSPAR...,ACABADOS,BAÑOS,SANITARIOS,OVALINES,ORANGE,IMPORTADO,https://promart.vteximg.com.br/arquivos/ids/38...,ovalin circular para sobreponer vidriotranspar...,"acabado brillante, tamaño del producto moderad...",Moderniza la decoración de tu baño con este ov...,Ovalín para sobreponer en mesada de baño hecho...,Se recomienda complementar la instalación del ...,Al momento de instalar no usar cemento ni arci...
1,10237,OVALIN CIRCULAR P/SOBREP ORANGE VIDRIO PAVONADO,ACABADOS,BAÑOS,SANITARIOS,OVALINES,ORANGE,IMPORTADO,https://promart.vteximg.com.br/arquivos/ids/50...,ovalin circular para sobreponer vidrio pavonad...,"acabado pavonado, tamaño del producto moderado...",Moderniza la decoración de tu baño con este ov...,Ovalín para sobreponer en mesada de baño hecho...,Se recomienda complementar la instalación del ...,Al momento de instalar no usar cemento ni arci...
2,10298,LLAVE DUCHA ORANGE FROST S/SALIDA,ACABADOS,BAÑOS,GRIFERIA DE BAÑO,LLAVE DUCHA,ORANGE,IMPORTADO,https://promart.vteximg.com.br/arquivos/ids/51...,llave ducha frost sin salida de la marca orang...,"acabado cromado, altura del producto 6.00 cm, ...",Dale un toque elegante a la grifería de tu duc...,Llave para ducha convencional de cuerpo interi...,"Previo a la compra, verificar si se puede adap...",Maniobrar con cuidado para evitar el deterioro...
3,10077,SILLA ESTAMBUL FIJA H-602F NEGRA,HOGAR Y DECO,MUEBLES,OFICINAS,SILLAS FIJAS,ORANGE,IMPORTADO,https://promart.vteximg.com.br/arquivos/ids/38...,silla estambul fija h-602f negra de la marca o...,"altura del producto 79.00 cm, ancho del produc...",p¡Dale un toque moderno y funcional a tus espa...,"Silla ideal para oficina, dormitorio o cualqui...","Silla fija, tiempo de vida estimado 2 años. Vi...",Estas sillas pueden ser limpiadas con un limpi...
4,10177,MESA DE ESTUDIO ESPAÑA CASTAÑO,HOGAR Y DECO,MUEBLES,OFICINAS,ESCRITORIOS RTA,POLITORNO,IMPORTADO,https://promart.vteximg.com.br/arquivos/ids/59...,mesa de estudio españa castaño de la marca pol...,"acabado satinado, altura del producto 76.00 cm...",h2Diseño elegante y funcional con la Mesa de e...,"Estructura de MDP, base del mismo material de ...","Mueble Fijo, no es necesario adosarlo a la par...",Se debe realizar la limpieza de sus muebles co...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46485,165369,BOXET DELUXE QUEEN GRIS,HOGAR Y DECO,MUEBLES,DORMITORIOS,COLCHONES,PARAISO,NACIONAL,NaN,boxet deluxe queen gris de la marca paraiso de...,"altura del producto 35 cm, ancho del producto ...",Boxet Paraíso Deluxe Queen Gris. Disfruta de l...,Descubre el nuevo Boxet Deluxe y organiza tu e...,Imágenes referenciales.,Revisar Cartilla de Usuario.
46486,165387,CAMA BOXET POCKET STAR QUEEN CHOCOLATE,HOGAR Y DECO,MUEBLES,DORMITORIOS,COLCHONES,PARAISO,NACIONAL,NaN,cama boxet pocket star queen chocolate de la m...,"altura del producto 65 cm, ancho del producto ...",Cama Boxet Paraíso Pocket Star Queen Chocolate...,Gracias a su diseño con ergosoft maximiza la s...,Imágenes referenciales.,Revisar Cartilla de Usuario.
46487,165375,DORMITORIO BOXET POCKET MAX QUEEN CHOCOLATE,HOGAR Y DECO,MUEBLES,DORMITORIOS,COLCHONES,PARAISO,NACIONAL,NaN,dormitorio boxet pocket max queen chocolate de...,"altura del producto 134 cm, ancho del producto...",Dormitorio Boxet Paraíso Pocket Max Queen Choc...,Pocket Max ha sido elaborado con resortes pock...,Imágenes referenciales.,Revisar Cartilla de Usuario.
46488,165376,CAMA BOXET POCKET STAR 1.5 PLAZAS CHOCOLATE,HOGAR Y DECO,MUEBLES,DORMITORIOS,COLCHONES,PARAISO,NACIONAL,NaN,cama boxet pocket star 1.5 plazas chocolate de...,"altura del producto 65 cm, ancho del producto ...",Cama Boxet Paraíso Pocket Star 1.5 Plazas Choc...,Gracias a su diseño con ergosoft maximiza la s...,Imágenes referenciales.,Revisar Cartilla de Usuario.
46489,165378,DORMITORIO BOXET POCKET STAR 1.5 PLAZAS CHAMPAGNE,HOGAR Y DECO,MUEBLES,DORMITORIOS,COLCHONES,PARAISO,NACIONAL,NaN,dormitorio boxet pocket star 1.5 plazas champa...,"altura del producto 135 cm, ancho del producto...",Dormitorio Boxet Paraíso Pocket Star 1.5 Plaza...,Gracias a su diseño con ergosoft maximiza la s...,Imágenes referenciales.,Revisar Cartilla de Usuario.

In [5]:
df['CHUNK_DESCRIPCION'] = df['CHUNK_DESCRIPCION'].fillna('')
df['CHUNK_CARACTERISTICAS'] = df['CHUNK_CARACTERISTICAS'].fillna('')
df['CHUNK_OBSERVACIONES'] = df['CHUNK_OBSERVACIONES'].fillna('')
df['CHUNK_RECOMENDACIONES'] = df['CHUNK_RECOMENDACIONES'].fillna('')

In [6]:
df["CHUNK"] = df["CHUNK_PRODUCTO"]+'. '+df["CHUNK_FICHA"]+'. '+df["CHUNK_DESCRIPCION"]+'. '+df["CHUNK_CARACTERISTICAS"]+'. '+df["CHUNK_OBSERVACIONES"]+'. '+df["CHUNK_RECOMENDACIONES"]

In [7]:
dx = df.sample(n=500)
dx

,SKU,DESCRIPCION,DES_DIV,DES_AREA,DES_DPTO,DES_LIN,DES_MARCA,DES_PROCE,URL,CHUNK_PRODUCTO,CHUNK_FICHA,CHUNK_DESCRIPCION,CHUNK_CARACTERISTICAS,CHUNK_OBSERVACIONES,CHUNK_RECOMENDACIONES,CHUNK
19131,131377,EXTENSION 3 TOMAS UNIV TIERRA 2MT NEGRO WERKEN,FERRETERIA,ELECTRICIDAD,CABLES,EXTENSIONES DOMESTIC,WERKEN,IMPORTADO,https://promart.vteximg.com.br/arquivos/ids/69...,extension 3 tomas univ tierra 2mt negro de la ...,"altura del producto 3.50 cm, ancho del product...",pLa Extensión 3 Tomas Universal Tierra 2m Werk...,Aislamiento PVC de color blanco con enchufe pl...,Es ideal para el trabajo liviano las 24 horas ...,Tener en cuenta siempre el rango de amperaje q...,extension 3 tomas univ tierra 2mt negro de la ...
24943,139789,CALZADO DE SEGURIDAD WARRIOR PPA TALLA 41 BATA,FERRETERIA,HERRAMIENTAS,SEGURIDAD INDUSTRIAL,CALZADO DE SEGURIDAD,BATA,NACIONAL,NaN,calzado de seguridad warrior ppa talla 41 de l...,"altura del producto 12.50 cm, ancho del produc...","Promart, cuenta con una amplia gama de calzado...",De diseño moderno y urbano. Fabricado en cuero...,Su duración dependerá de las condiciones de us...,Realizar la limpieza con paño húmedo.,calzado de seguridad warrior ppa talla 41 de l...
30363,147723,CARRETE - CABLE DESNUDO 16 MM2,FERRETERIA,ELECTRICIDAD,CABLES,CABLES POR METRO,CELSA,NACIONAL,NaN,carrete - cable desnudo 16 mm2 de la marca cel...,"altura del producto 0.31 cm, ancho del product...","Usos para conexiones a tierra, circuito aéreo ...",Excelente calidad. Resistencia y durabilidad.,Producto se vende por metro lineal.,"Ideal para instalaciones residenciales, en el ...",carrete - cable desnudo 16 mm2 de la marca cel...
24728,140012,"MONITOR LCD 2.4"" COLOR BEBE VM2251 VTECH",FERRETERIA,ELECTRICIDAD,SEGURIDAD,CAMARAS DE SEGURIDAD,VTECH,NACIONAL,NaN,"monitor lcd 2.4"" color bebe vm2251 de la marca...","altura del producto 13.00 cm, ancho del produc...",Porque la seguridad de tu bebé es tu prioridad...,"Tecnología 2.4 GHz. Monitor LCD 2.4"" a colores...",Es importante que se asegure que la velocidad ...,Asegurarse de que su uso sea dentro del rango ...,"monitor lcd 2.4"" color bebe vm2251 de la marca..."
7237,78962,SET DE BAÑO ORANGE X 4PZAS CANNES,ACABADOS,BAÑOS,ORGANIZACION DE BAÑO,SETS ADOSADOS,ORANGE,IMPORTADO,https://promart.vteximg.com.br/arquivos/ids/28...,set de baño x 4pzas cannes de la marca orange ...,"acabado brillante, altura del producto 7.20 cm...",Complementa la decoración de tu baño con los a...,,Instalar solo en paredes de material noble o m...,"Para la limpieza, pasa un paño húmedo por toda...",set de baño x 4pzas cannes de la marca orange ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6872,75179,SALIDA D/ DUCHA TREBOL IRIS,ACABADOS,BAÑOS,GRIFERIA DE BAÑO,ACCESORIOS Y REPUESTOS DE GRIFERIA DE BAÑOS,TREBOL,NACIONAL,https://promart.vteximg.com.br/arquivos/ids/51...,salida d ducha iris de la marca trebol del ar...,"acabado cromado, tamaño del producto pequeño, ...",Moderna y económica salida de ducha de Trebol....,Salida de ducha hecho de cuerpo de Bronce con ...,Salida de ducha apta para agua caliente y fría...,Maniobrar con cuidado para evitar el deterioro...,salida d ducha iris de la marca trebol del ar...
23353,137686,ONE PIECE VAINSA MODENA C/ASIENTO BLANCO,ACABADOS,BAÑOS,SANITARIOS,ONE PIECE,VAINSA,NACIONAL,NaN,one piece modena con asiento blanco de la marc...,"acabado esmaltado, tamaño del producto grande,...",p!Transforma tu baño en un oasis de elegancia ...,Con triple jet de descarga. Con recubrimiento ...,"Este Inodoro es de una sola pieza, es decir, t...",Limpiar con paño húmedo. Es recomendable que s...,one piece modena con asiento blanco de la marc...
33000,151642,REFRIGERADORA LG GT31WPP 314L PLATEADA,HOGAR Y DECO,ELECTRO HOGAR,LINEA BLANCA,REFRIGERADORAS,LG,NACIONAL,NaN,refrigeradora gt31wpp 314l plateada de la marc...,"acabado no aplica, tamaño del producto grande,...",La Refrigeradora LG GT31WPP Top Freezer Door C...,Motor Smart Inverter Compressor. Multi Air Flo...,10 años de garantía en el motor.,"Para un correcto funcionamiento de su equipo, ...",refrigeradora gt31wpp 314l plateada de la marc...
38030,157740,I&O-KIT LIMPIA AROS 500ML + CEPILLO LLANTAS SONAX,FERRETERIA,HERRAMIENTAS,AUTOMOTRIZ,LIMPIEZA Y ADITIVOS,SONAX,NACIONAL,NaN,i&o-kit limpia aros 500ml cepillo llantas de...,"altura del producto 26.00 cm, ancho del produc...","Limpiador de aros, llantas especial para todo ...",Limpiador para aros de acero y de metales lige...,"Guardar el producto en un lugar fresco, seco y...",Leer las indicaciones de cómo aplicar el produ...,i&o-kit limpia aros 500ml cepillo llantas de...
9650,104760,TACO MIRAMAR,ACABADOS,PISOS Y REVESTIMIENTOS,DECORADOS,LISTELOS,KANTU,NACIONAL,https://promart.vteximg.com.br/arquivos/ids/42...,taco miramar de la marca kantu del area de pis...,"acabado brillante, altura del producto 9.70 cm...","Un producto elaborado a base de cerámico, hech...","Puede usarse con cualquier formato, así la con...",Arcilla cocida a altas temperaturas.,Cubrir con cinta de papel antes de fraguar. Co...,taco miramar de la marca kantu del area de pis...

In [9]:
dx.to_csv('output.csv', columns=['SKU','CHUNK'], index=False)

In [8]:
docs = (df["CHUNK_PRODUCTO"]+'. '+df["CHUNK_FICHA"]+'. '+df["CHUNK_DESCRIPCION"]+'. '+df["CHUNK_CARACTERISTICAS"]+'. '+df["CHUNK_OBSERVACIONES"]+'. '+df["CHUNK_RECOMENDACIONES"]).tolist()
docs

['ovalin circular para sobreponer vidriotransparente de la marca orange del area de baños para los sanitarios de la linea ovalines de procedencia importado. acabado brillante, tamaño del producto moderado, altura del producto 14.50 cm, ancho del producto 42.00 cm, profundidad del producto 42.00 cm, volumen del producto 25578, diametro del producto 42.00 cm, ean 2000000102368, medidas 42.00x42.00x14.50, tipo de producto ovalín, modelo transparente, color transparente, material vidrio, garantía 1 año, procedencia importado, país de origen china. Moderniza la decoración de tu baño con este ovalín de vidrio sobre encimera transparente. Fabricado íntegramente con vidrio templado de la más alta calidad y resistencia.. Ovalín para sobreponer en mesada de baño hecho al 100%  de vidrio transparente, de forma circular, con un diámetro total de 42 cms, viene sin rebose, perforación para desagüe de 2".. Se recomienda complementar la instalación del ovalín comprando grifería alta al mueble o a la pared, un vanitorio y accesorios de instalación tales como desagüe y trampa, No empotrar. Al momento de la instalación ya debe estar listo el tablero en donde se va a sobreponer el ovalín.. Al momento de instalar no usar cemento ni arcilla para adherirlo a la mesada, simplemente sellar con silicona preferentemente transparente y con fungicida, se puede limpiar con detergente o una solución de agua + jabón aplicando con una esponja o paños de poliseda o microfibra, no limpiar con  ácidos y/o material abrasivo.',
 'ovalin circular para sobreponer vidrio pavonado de la marca orange del area de baños para los sanitarios de la linea ovalines de procedencia importado. acabado pavonado, tamaño del producto moderado, altura del producto 14.50 cm, ancho del producto 42.00 cm, profundidad del producto 42.00 cm, volumen del producto 25578, diametro del producto 42.00 cm, ean 2000000102375, medidas 42.00x42.00x14.50, tipo de producto ovalín, modelo pavonado, color transparente, material vidrio, garantía 1 año, procedencia importado, país de origen china. Moderniza la decoración de tu baño con este ovalín de vidrio sobre encimera pavonado. Fabricado íntegramente con vidrio templado de la más alta calidad y resistencia.. Ovalín para sobreponer en mesada de baño hecho al 100%  de vidrio pavonado, de forma circular, con un diámetro total de 42 cms, viene sin rebose, perforación para desagüe de 2".. Se recomienda complementar la instalación del ovalín comprando grifería alta al mueble o a la pared, un vanitorio y accesorios de instalación tales como desagüe y trampa, No empotrar. Al momento de la instalación ya debe estar listo el tablero en donde se va a sobreponer el ovalín.. Al momento de instalar no usar cemento ni arcilla para adherirlo a la mesada, simplemente sellar con silicona preferentemente transparente y con fungicida, se puede limpiar con detergente o una solución de agua + jabón aplicando con una esponja o paños de poliseda o microfibra, no limpiar con  ácidos y/o material abrasivo.',
 'llave ducha frost sin salida de la marca orange del area de baños para los griferia de baño de la linea llave ducha de procedencia importado. acabado cromado, altura del producto 6.00 cm, ancho del producto 6.00 cm, profundidad del producto 6.66 cm, volumen del producto 239.76, ean 612049000004, medidas 6.00x6.66x6.00, tipo de producto llave, modelo frost, color plata, material latón/acrílico, garantía 1 año, procedencia importado, país de origen china. Dale un toque elegante a la grifería de tu ducha con la llave Frost de Orange.. Llave para ducha convencional de cuerpo interior de latón con acabado cromado en el exterior, sistema de cierre medio giro. Altamente resistente a la corrosión. Viene con perilla de acrílico con diseño convencional. Previo a la compra, verificar si se puede adaptar al sistema de ducha que tenga en casa, solo se instala en sistemas nuevos de agua fría. Medida en profundidad expresada solo se considera de la parte visible, es decir, de la pared hacia el frente. Puede complementar su compra con una salida de ducha.. Maniobrar con cuidado para evitar el deterioro de la llave, limpiar con un paño seco, en caso de acumulación de sarro limpiar con vinagre blanco y agua tibia, para mantener el brillo del cromado no limpiar con material abrasivo.',
 'silla estambul fija h-602f negra de la marca orange del area de muebles para los oficinas de la linea sillas fijas de procedencia importado. altura del producto 79.00 cm, ancho del producto 53.00 cm, profundidad del producto 50.00 cm, volumen del producto 209350, diametro del producto 0, ean 2000000100777, medidas 53.00x50.00x79.00, tipo de producto silla, modelo estambul, color negro, material acero, garantía 1 año, procedencia importado, país de origen china. p¡Dale un toque moderno y funcional a tus espacios con la Silla fija Estambul Negra Orange! Es perfecta para oficinas, dormitorios o cualquier rincón de tu hogar. Con una estructura robusta de acero color negro y un diseño elegante, combina estilo y comodidad. Su asiento y respaldar están acolchados con espuma y revestidos en tela tapiz negra, garantizando un confort excepcional en cada uso. Además, es apilable, lo que la convierte en una opción práctica para ahorrar espacio. Características y beneficios de la Silla fija Estambul Negra Orange: Estructura de acero resistente que soporta hasta 120 kg.br• Diseño moderno y elegante, ideal para cualquier ambiente interior.br• Asiento y respaldar tapizados en tela negra, cómodos y fáciles de limpiar.br• Apilable para un almacenamiento práctico y eficiente.. Silla ideal para oficina, dormitorio o cualquier espacio de la casa. Estructura de acero color negro, base de 4 patas, asiento de MDF con espuma revestido con tela tapiz color negro, respaldar de MDF con espuma revestido con tela tapiz color negro.. Silla fija, tiempo de vida estimado 2 años. Viene sin reposa brazos.. Estas sillas pueden ser limpiadas con un limpia telas o protector de telas, tambien se puede limpiar con paño húmedo o seco 1 o 2 veces por semana.',
 'mesa de estudio españa castaño de la marca politorno del area de muebles para los oficinas de la linea escritorios rta de procedencia importado. acabado satinado, altura del producto 76.00 cm, ancho del producto 152.00 cm, profundidad del producto 116.50 cm, volumen del producto 1345808, diametro del producto 0, ean 7898936462916, medidas 152.00x116.50x76.00, tipo de producto escritorio, modelo españa, color marrón, material melamina, garantía 1 año, procedencia importado, país de origen brasil. h2Diseño elegante y funcional con la Mesa de estudio España Castañoh2pLa strongmesa de estudio España Castaño/strong tiene un diseño elegante y funcional que se adapta a cualquier espacio. Su estructura es sólida y resistente, lo que garantiza su durabilidad. Esta mesa tiene una amplia superficie de trabajo que te permite estudiar, trabajar o hacer tus hobbies sin problemas. Además, cuenta con tres cajones espaciosos y dos puertas con estantes interiores, donde puedes guardar tus materiales de estudio, libros, documentos y otros objetos. Su acabado en castaño y aliso le da un toque de estilo a tu habitación, convirtiendo la mesa de estudio España Castaño en un mueble imprescindible para cualquier hogar. Características de la Mesa de estudio España Castañoh2ulli Altura: 76 cm x Ancho 152 cm x Profundidad: 116.5 cmli Escritorio amplio en forma de L.li Fabricado en MDP de gran durabilidad.li Con acabado en pintura UV.li Resistencia hasta 50kg.li Incluye manual y kit de armado./ulh2Materiales de alta calidad y resistencia con la Mesa de estudio España CastañopLa strongmesa de estudio España Castaño/strong está hecha con materiales de alta calidad y resistencia, lo que la convierte en un mueble duradero y confiable. Su estructura está fabricada en MDP, son materiales que garantizan su resistencia y estabilidad. Además, su superficie es fácil de limpiar y mantener, lo que la convierte en un mueble práctico para el uso diario. Con la mesa de estudio España Castaño, no tendrás que preocuparte por el desgaste o deterioro con el tiempo, ya que está diseñada para durar.. Estructura de MDP, base del mismo material de la estructura con insertos de plástico para evitar el contacto directo con el piso, viene con 3 cajones en un lado del mueble y un espacio para guardar diversos objetos.. Mueble Fijo, no es necesario adosarlo a la pared. Estructura llega hasta el piso. Medidas de profundidad 70 y 46.5 cm, Medidas de Ancho 37.5 y 114 cm (Medidas referenciales).. Se debe realizar la limpieza de sus muebles con una franela suave, levemente húmeda, con agua y jabón neutro, seguido de franela seca. No haga adaptaciones, reformas en el mueble o montaje que no corresponda al propuesto en el manual de instrucciones.',
 'papelera 3lt con pedal acero inox cr de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado brillante, altura del producto 25.70 cm, ancho del producto 17.00 cm, profundidad del producto 23.00 cm, volumen del producto 10048.7, diametro del producto 17.00 cm, ean 2000000102238, medidas 17.00x23.00x25.70, tipo de producto papelera, color plata, material acero inoxidable/plástico, garantía 1 año, procedencia importado, país de origen china. pMantén tu hogar limpio y organizado con la Papelera de Acero Inoxidable 3 litros Orange Plata con Pedal. Esta papelera combina elegancia y funcionalidad, con un diseño cilíndrico de acero inoxidable y base de plástico negro. Su pedal de acero permite una apertura fácil y sin contacto manual, mientras que su capacidad de 3 litros la hace ideal para uso doméstico. Con un acabado brillante y bisagras resistentes, esta papelera es la solución perfecta para mantener tu espacio ordenado y limpio. Características de la Papelera de Acero Inoxidable 3 litros Orange Plata con Pedal:ul liDiseño elegante y funcional. liCapacidad de 3 litros. liPedal de acero para apertura sin contacto. liAcabado brillante y resistente. liIdeal para uso doméstico./ul. Tacho de acero inoxidable con base de plástico color negro, pedal de acero y superficie de plástico antideslizante, cuerpo de acero inoxidable de forma cilíndrica, tapa metálica color negro, internamente viene con un depósito de plástico con mango o sujetador de acero. Bisagras de acero cubierto con un cuerpo de plástico con sujetador de acero.. Uso doméstico, no exceder la capacidad del producto.. Se recomienda limpiar con un limpiavidrios, una solución de agua + jabón o productos especializado para la limpieza de metales, aplicándolo con un paño de  poliseda o de microfibra semihumedo. Se recomienda usar en superficies planas.',
 'papelera 5lt con pedal acero inox cr de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado brillante, altura del producto 27.50 cm, ancho del producto 20.00 cm, profundidad del producto 27.00 cm, volumen del producto 14850, diametro del producto 20.00 cm, ean 2000000102245, medidas 20.00x27.00x27.50, tipo de producto papelera, modelo con pedal, color plata, material acero inoxidable/plástico, garantía 1 año, procedencia importado, país de origen china. Resistente papelera fabricada en acero inoxidable para colocar en el baño. Tiene una capacidad de 5 litros.. Tacho de acero inoxidable con base de plástico color negro, pedal de acero y superficie de plástico antideslizante, cuerpo de acero inoxidable de forma cilíndrica, tapa del mismo material del cuerpo, internamente viene con un depósito de plástico con mango o sujetador de acero. Bisagras de acero cubierto con un cuerpo de plástico con sujetador de acero.. Uso doméstico, no exceder la capacidad del producto.. Se recomienda limpiar con un limpiavidrios, una solución de agua + jabón o productos especializado para la limpieza de metales, aplicándolo con un paño de  poliseda o de microfibra semihumedo. Se recomienda usar en superficies planas.',
 'repisa baño multifuncional cr de la marca orange del area de baños para los organizacion de baño de la linea repisas de baño de procedencia importado. acabado brillante, tamaño del producto moderado, altura del producto 54.50 cm, ancho del producto 43.50 cm, profundidad del producto 25.30 cm, volumen del producto 59979.975, ean 2000000102269, medidas 43.50x25.30x54.50, tipo de producto repisa, modelo multifuncional, color plata, material acero, garantía 1 año, procedencia importado, país de origen china. Ahorra espacio y encuentra fácilmente tus productos y utensilios de higiene con esta repisa que Promart tiene para ti.. Estructura de metal, repisas y accesorios hecho del mismo material al 100%,, cuenta con 2 toalleros y 2 repisas para distribuir mejor los productos, estas repisas viene con perforaciones para evitar acumulación de agua. Ahorra espacio, ideal para almacenar tus utensilios de higiene.. Producto viene para armar, uso solo para interiores y exclusivamente doméstico.. Limpiar el producto con un protector de acero una vez por semana o de acuerdo al uso o con una solución de agua + jabón, aplicando con esponja o paños de microfibra o poliseda.',
 'bateria 7lbi 7plc.12v. de la marca capsa del area de herramientas para los automotriz de la linea baterias de procedencia nacional. volumen del producto 0, ean 7703129651261, color no aplica, garantía 1 año, procedencia nacional. . . . ',
 'bateria 5u1r 5plc.12v. de la marca capsa del area de herramientas para los automotriz de la linea baterias de procedencia nacional. volumen del producto 0, ean 7703129666371, color no aplica, garantía 1 año, procedencia nacional. . . . ',
 'bateria 13api.13 plc.12v de la marca capsa del area de herramientas para los automotriz de la linea baterias de procedencia nacional. altura del producto 22.70 cm, ancho del producto 25.50 cm, profundidad del producto 17.30 cm, volumen del producto 10014.105, ean 7703129639597, medidas 25.50x17.30x22.70, tipo de producto batería, modelo 13api, color negro, material polipropileno, garantía 1 año, procedencia nacional, país de origen colombia. Con un gran diseño de manija para facilitar la instalación y cambio, mayor resistencia de la rejilla de corrosión y sobrecarga; además, de un potente arranque y desempeño, y un infaltable atenuador de llama para prevenir riesgo de explosiones. Sin duda, un producto que garantiza la perduración y buen funcionamiento de nuestro vehículo.. Batería de alto rendimiento compuesta de plomo, calcio y plata, de gran calidad y efectividad. Ideal para autos gasolineros, petrolero y GNV. Ideal para motores 1800 a 2400. Poste positivo al lado derecho (desde el frente). Adecuado para uso de transporte particular y público. Arranque en caliente +22°. Producto corrosivo, de ácido sulfúrico.. Leer indicaciones del producto antes de usar la batería. Realizar el mantenimiento de batería y revisión del vehículo cada mes (uso público) y cada 3 meses (uso particular). Realizar el mantenimiento en servicios autorizados y no manipular el producto. Revisión el sistema eléctrico del vehículo, mantener limpia y seca la cubierta y caja de la batería.',
 'bateria 11apcgi/11plc.12v de la marca capsa del area de herramientas para los automotriz de la linea baterias de procedencia nacional. volumen del producto 0, ean 7703129658727, color no aplica, garantía 1 año, procedencia nacional. . . . ',
 'bateria 13apcgi 13plc.12v. de la marca capsa del area de herramientas para los automotriz de la linea baterias de procedencia nacional. altura del producto 22.50 cm, ancho del producto 30.50 cm, profundidad del producto 17.30 cm, volumen del producto 11872.125, ean 7703129651223, medidas 30.50x17.30x22.50, tipo de producto batería, modelo 13apcgi, color negro, material polipropileno, garantía 1 año, procedencia nacional, país de origen colombia. La batería es el elemento fundamental para el funcionamiento de un vehículo. Por ello, te traemos esta batería que reúne poder e innovación tecnológica en su interior, para asegurarte un óptimo desempeño. Al ser fabricado con los más altos estándares de calidad, te permitirá un arranque en frío fiable en cualquier clima. Puede ser utilizado en todo tipo de autos, ya sean modernos o antiguos.. Batería de alto rendimiento compuesta de plomo, calcio y plata, de gran calidad y efectividad. Ideal para autos gasolineros y GNV. Ideal para motores 1500 a 2000. Poste positivo al lado derecho (desde el frente). Adecuado para uso de transporte particular y público. Arranque en caliente +22°.. Producto corrosivo, de ácido sulfúrico.. Leer indicaciones del producto antes de usar la batería. Realizar el mantenimiento de batería y revisión del vehículo cada mes (uso público) y cada 3 meses (uso particular). Realizar el mantenimiento en servicios autorizados y no manipular el producto. Revisión el sistema eléctrico del vehículo, mantener limpia y seca la cubierta y caja de la batería.',
 'bateria 15apcgi 15plc.12v. de la marca capsa del area de herramientas para los automotriz de la linea baterias de procedencia nacional. altura del producto 22.50 cm, ancho del producto 30.50 cm, profundidad del producto 17.30 cm, volumen del producto 11872.125, ean 7703129651230, medidas 30.50x17.30x22.50, tipo de producto batería, modelo 15apcgi, color negro, material polipropileno, garantía 1 año, procedencia nacional, país de origen colombia. Promart, presenta una línea de baterías y accesorios para el automóvil, con una calidad Premium. Reúne los mejores e innovadores productos para su disposición.Las baterías 15APCGI, son de bajo mantenimiento, con capacidad de 90Ah. Excelente diseño de manija para su fácil instalación y cambio. Tienen un alto equipamiento y tecnología (Sistema robotizado en ensamble y material activo), por ende mayor duración.. Batería de alto rendimiento compuesta de plomo, calcio y plata, de gran calidad y efectividad. Ideal para autos gasolineros, petrolero y GNV. Ideal para motores 2000 a 3300. Poste positivo al lado derecho (desde el frente). Adecuado para uso de transporte particular y público. Arranque en caliente +22°. Producto corrosivo, de ácido sulfúrico.. Leer indicaciones del producto antes de usar la batería. Realizar el mantenimiento de batería y revisión del vehículo cada mes (uso público) y cada 3 meses (uso particular). Realizar el mantenimiento en servicios autorizados y no manipular el producto. Revisión el sistema eléctrico del vehículo, mantener limpia y seca la cubierta y caja de la batería.',
 'bateria 1135/11plc.12v de la marca capsa del area de herramientas para los automotriz de la linea baterias de procedencia nacional. volumen del producto 0, ean 7703129654071, color no aplica, garantía 1 año, procedencia nacional. . . . ',

In [9]:
from sentence_transformers import SentenceTransformer

# Cargar modelo localmente
model = SentenceTransformer(MAIN_ROUTE+"/modelos/all-MiniLM-L6-v2")
embeddings = model.encode(docs, show_progress_bar=True, convert_to_numpy=True)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Batches: 100%|██████████| 1453/1453 [03:15<00:00,  7.45it/s]

In [10]:
import numpy as np
# ---------- 3) Normalizar similaridad coseno ----------
def normalize(x: np.ndarray):
    norms = np.linalg.norm(x, axis=1, keepdims=True)
    return x / (norms + 1e-10)

embeddings = normalize(embeddings)

In [33]:

np.save(MAIN_ROUTE+"/embeddings/CHUNK_TOTAL.npy", embeddings)

In [11]:
import faiss
from typing import List

# ---------- 1) Datos de ejemplo ----------
doc_ids = [f"doc_{i}" for i in range(len(docs))]


# ---------- 4) Crear índice FAISS (IndexFlatIP para coseno con vectores normalizados) ----------
d = embeddings.shape[1]
index = faiss.IndexFlatIP(d)        # producto interno
index.add(embeddings)              # añade vectores

id_to_doc = dict(zip(range(len(doc_ids)), docs))


# ---------- 5) Función de búsqueda ----------
def retrieve(query: str, k: int = 3) -> List[str]:
    q_emb = model.encode([query], convert_to_numpy=True)
    q_emb = normalize(q_emb)
    D, I = index.search(q_emb, k)  # D: similitud, I: índices
    results = []
    for idx in I[0]:
        if idx == -1: continue
        results.append(id_to_doc[idx])
    return results

In [12]:
# ---------- 6) Ejemplo RAG: consulta + prompt para SLM ----------
query = "casa ducha rompio"
retrieved = retrieve(query, k=3)
context = "\n\n".join(retrieved)

# Construir prompt para SLM 
prompt = f"""
Contexto (documentos relevantes):
{context}

Pregunta: {query}

Usando solo la información del contexto, responde de forma concisa y paso a paso. Si la información no está, di que no hay suficientes detalles.
"""

print(prompt)

Contexto (documentos relevantes):
plato de cena 26cm azul de la marca kaz home del area de cocina para los menaje de la linea vajilla y fuentes de procedencia nacional. volumen del producto 0, ean 2800005012934, color no aplica, garantía 1 año, procedencia nacional. . . .

pe fron dob corred crist temp ducha 141-150 alt180 de la marca compas del area de baños para los tinas e hidromasajes de la linea puertas para duchas de procedencia nacional. volumen del producto 0, ean 2000000275406, color no aplica, garantía 1 año, procedencia nacional. . . .

casaca/pantalon para lluvia 304 amar xl de la marca delta plus del area de herramientas para los seguridad industrial de la linea ropa de trabajo de procedencia nacional. volumen del producto 0, ean 3295249128272, color no aplica, garantía 1 año, procedencia nacional. . . .

Pregunta: casa ducha rompio

Usando solo la información del contexto, responde de forma concisa y paso a paso. Si la información no está, di que no hay suficientes detalles.

In [27]:
import spacy
from spacy.lang.es.stop_words import STOP_WORDS

VERBOS_RUIDO = ["necesitar", "querer", "buscar", "requerir", "comprar", "utilizar",'cosito','adecuar','cualquier','funcionar','usar','']

nlp = spacy.load("es_core_news_sm")

def palabras_relevantes(texto):
    doc = nlp(texto)

    palabras = []
    for token in doc:
        if (token.pos_ in ["NOUN", "VERB", "PROPN"]) and token.text.lower() not in STOP_WORDS:
            lemma = token.lemma_.lower()
            if lemma not in VERBOS_RUIDO:
                palabras.append(lemma)

    return " ".join(palabras)

# Ejemplo
oracion = "dentro de mi casa tengo una ducha, necesito el cosito para la ducha que se rompio."
resultado = palabras_relevantes(oracion)
print(resultado)

casa ducha ducha rompio

In [24]:
dp = pd.read_csv("preguntas-respuestas-v1.1.csv",delimiter=";", encoding='utf-8')

dp

,SKU,CHUNK,Pregunta,Respuesta
0,19812,papelera buzon 10 con pedal de la marca durap...,Necesito una papelera con pedal de preferencia...,Tenemos papelera buzon 10 con pedal duraplast.
1,149655,piso tec atenas mrfl r.sma 45x45 2.23m2 de la ...,como puedo limpiar un piso ceramico?,Se recomienda limpiar con un paño humedecido.
2,153567,lámpara de mesa solo2 1x40w de la marca eglo d...,"tengo una lampara de mesa, que foco utiliza?",cualquier bombilla con castillo E27.
3,149436,locker plastico abs lp102 llave doblepin verd ...,busco un casillero con llave,Tenemos un locker plastico abs.
4,126558,lirio blanco - 91 cm de la marca orange del ar...,como puedo limpiar mis flores artificailes?,"Primero quita el polvo con un plumero, luego e..."
5,33021,reflector portatil x 500w de la marca total de...,¿Tienen un focos o luces portátil para exteri...,"Sí, contamos con un reflector portátil de 500W..."
6,146725,cierrapuerta modelo 3005 de la marca yale del ...,¿Tienen chapa con las tres b de bueno bonito ...,"Sí, contamos con el cierrapuertas Yale modelo ..."
7,152300,ramo de peonias rosas de la marca atmosphera d...,¿Tienes esos ramos de flores de plastico o f...,"Sí, contamos con el ramo de peonías rosas Atmo..."
8,158016,silla zero gravedad metal textileno gris silve...,¿Tienes una silla de playa que se reclinable o...,"Sí, contamos con la silla Zero Gravedad de met..."
9,145793,atornillador gsr 18v-60fc 2bat de la marca bos...,¿necesito un atornillador que no tenga cbale e...,"Sí, contamos con el atornillador Bosch GSR 18V..."
10,162470,i&o-headphones wireless akz-01 de la marca sm ...,¿Tienen audífonos inalámbricos con blultooth ...,"Sí, contamos con los audífonos inalámbricos AK..."
11,127423,"valvula esfera 1/2"" pegar duke de la marca sm ...",¿Tienen esa cosa que se pone en el tubo para a...,"Sí, contamos con la válvula esfera 1/2"" Pegar ..."
12,128915,bestway sillon inflable color surtido 112 cm d...,¿Tienes un sillón que se pueda inflablar y des...,"Sí, contamos con el sillón inflable Bestway de..."
13,14161,"pack x5 disco corte ac. 7""skil de la marca ski...",¿Tienen discos de corte de 7 pulgadas para amo...,"Sí, contamos con el pack de 5 discos de corte ..."
14,108973,atornillador 12v th-cd 12-2 li mp de la marca ...,"¿Tienen un taladro atornillador pequeño, sin c...","Sí, contamos con el atornillador Einhell TH-CD..."
15,162315,roller cortable blackout gris 120x180 cm de la...,¿Tienen una cortina que se pueda subir y bajar...,"Sí, contamos con el roller blackout 120x180 cm..."
16,26275,fotomural friendship 2 paños de la marca decop...,¿Tienen algún fotomural decorativo en varios p...,"Sí, contamos con el fotomural Friendship de 2 ..."
17,142226,xiaomi tv 50 pulgadas uhd p1 l50m6 mtk de la m...,¿Tienen un televisor de 50 pulgadas con resolu...,"Sí, contamos con el Xiaomi TV de 50"", resoluci..."
18,133453,taladro de banco 32mm 2hp de la marca kaili de...,¿Tienen un taladro de banco potente que tenga ...,"Sí, contamos con el taladro de banco Kaili de ..."
19,138403,bateria 40b19l(35ah/330a) de la marca bosch de...,¿Tienen una batería de auto de 35 amperios-hor...,"Sí, contamos con la batería Bosch 40B19L de 35..."
20,61243,bloq.de humedad y salitre 1gl de la marca maje...,¿Tienen algún producto para cubrir superficies...,"Sí, contamos con el bloqueador de humedad y sa..."
21,133058,trampa multiposicion para lavatorio y lavadero...,¿Tienen una trampa multiposición para lavatori...,"Sí, contamos con la trampa multiposición Cofle..."
22,96733,"espatula flexible 5"" de la marca stanley del a...",¿Tienen una espátula flexible para trabajos de...,"Sí, contamos con la espátula flexible de 5"" St..."
23,120115,caja chica roja con llave de la marca werken d...,¿Tienen una caja de seguridad pequeña con llav...,"Sí, contamos con la caja de seguridad Werken C..."
24,22245,plywood moldaje b/cp 9mm 1.22x2.44m de la marc...,¿Tienen triplay fenólico de 9 mm que sea resis...,"Sí, contamos con el triplay fenólico Moldeja B..."
25,144128,rl cable thw-90 450/750 v 12 awg blanco 5m de ...,¿Cuál es la diferencia entre el cable THW-90 y...,El cable THW-90 es ideal para instalaciones fi...
26,157026,piso cementicio grey cenizo 120x60 2.16m2 de l...,¿Cómo se comporta el piso cementicio en áreas ...,El piso cementicio Grey Cenizo es excepcionalm...
27,134222,pulverizador 2lt de la marca ferticorp del are...,¿El pulverizador ferticorp es apto para desinf...,"Sí, nuestro pulverizador puede realizar un roc..."
28,121599,prd est trama mix beige 30x60 ext 1.63 de la m...,¿La placa celima es adecuada para revestir par...,"Sí, la placa Trama Mix Beige es ideal para rev..."
29,134749,piscina estructural circular 15232lt - 427x122...,¿La piscina circular es fácil de instalar y se...,"Sí, la piscina estructural circular es fácil d..."
30,149697,"letrero peligro alto voltaje, 30 x 40 cm de la...",¿Los letreros de seguridad son adecuados para ...,"Sí, este letrero de peligro alto voltaje es ve..."
31,133344,desarmador con accesorios 29pcs de la marca ka...,¿Los desarmadores kamasa son versátil y adecua...,"Sí, este desarmador es ideal para apretar y af..."
32,143455,organizador sobre inodoro haya de la marca tuh...,¿El organizador de inodoro es funcional y resi...,"Sí, este organizador es muy funcional y está d..."
33,151771,vanitorio brescia caramelo de la marca bianely...,¿Qué cuidados debo tener con los vanitorios pa...,Para mantener su vanitorio Brescia en excelent...
34,161680,taper 1.2l con cubiertos de la marca sm del ar...,¿El taper de cubiertos es adecuado para llevar...,"Sí, este taper de 1.2 litros es ideal para lle..."
35,117298,fiddler audifono con microfono azul de la marc...,¿Los audífonos fiddler son compatibles con mis...,¡Absolutamente! Los audífonos Fiddler con micr...
36,82863,zocalo porcelanato esmaltado line stone 7.3x60...,¿El zócalo de porcelanato es adecuado para pro...,"Sí, el zócalo porcelanato esmaltado Line Stone..."
37,118259,papelera magaly #20 metalizada de la marca rey...,¿La papelera metalizada es para uso en la coci...,¡Por supuesto! La papelera Magaly está diseñad...
38,14455,batería s560dh (60ah/460a) de la marca bosch d...,¿Qué precauciones debo tener al instalar la ba...,"Al instalar la batería S560DH, es crucial empe..."
39,151492,command gancho ancla niquel satinado decorativ...,¿El gancho ancla de niquel es fácil de instala...,"Sí, se adhiere firmemente sin dañar la pared y..."
40,158994,lámpara led ballena de la marca orange del are...,¿La lámpara ballena es adecuada para la habita...,"Sí, la lámpara LED Ballena es perfecta para ha..."
41,151737,"disco multicorte 180x1.6x22.23 7""x1/16""x7/8"" d...",¿El disco multicorte norton es versátil y pued...,"Sí, este disco multicorte es ideal para cortar..."
42,162041,kit tal dhp485z dtd153z 2bat carg mp de...,¿El kit de taladro makita es adecuado para tra...,"Sí, este kit Makita es perfecto para trabajos ..."
43,153140,pegamentos chemita gris extrafuerte x 25 kg de...,¿El pegamento chemita sirve para enchapar en a...,"Sí, el pegamento Chemita es ideal para enchapa..."
44,147622,colgante montefio plata de la marca eglo del ...,¿la luz colgante es adecuado para iluminar gra...,"Sí, el colgante Montefio es perfecto para ilum..."

In [28]:
dp['NER'] = dp['Pregunta'].apply(palabras_relevantes)
dp

,SKU,CHUNK,Pregunta,Respuesta,NER
0,19812,papelera buzon 10 con pedal de la marca durap...,Necesito una papelera con pedal de preferencia...,Tenemos papelera buzon 10 con pedal duraplast.,papelera pedal preferencia color
1,149655,piso tec atenas mrfl r.sma 45x45 2.23m2 de la ...,como puedo limpiar un piso ceramico?,Se recomienda limpiar con un paño humedecido.,limpiar piso
2,153567,lámpara de mesa solo2 1x40w de la marca eglo d...,"tengo una lampara de mesa, que foco utiliza?",cualquier bombilla con castillo E27.,lampara mesa foco
3,149436,locker plastico abs lp102 llave doblepin verd ...,busco un casillero con llave,Tenemos un locker plastico abs.,casillero llave
4,126558,lirio blanco - 91 cm de la marca orange del ar...,como puedo limpiar mis flores artificailes?,"Primero quita el polvo con un plumero, luego e...",limpiar flor
5,33021,reflector portatil x 500w de la marca total de...,¿Tienen un focos o luces portátil para exteri...,"Sí, contamos con un reflector portátil de 500W...",foco luz exteriores funcionir
6,146725,cierrapuerta modelo 3005 de la marca yale del ...,¿Tienen chapa con las tres b de bueno bonito ...,"Sí, contamos con el cierrapuertas Yale modelo ...",chapa b calidad abrir cerrar puerta ventana casa
7,152300,ramo de peonias rosas de la marca atmosphera d...,¿Tienes esos ramos de flores de plastico o f...,"Sí, contamos con el ramo de peonías rosas Atmo...",tener ramo flor plastico flor color decorar ca...
8,158016,silla zero gravedad metal textileno gris silve...,¿Tienes una silla de playa que se reclinable o...,"Sí, contamos con la silla Zero Gravedad de met...",tener silla playa pese usar él terraza playa r...
9,145793,atornillador gsr 18v-60fc 2bat de la marca bos...,¿necesito un atornillador que no tenga cbale e...,"Sí, contamos con el atornillador Bosch GSR 18V...",atornillador cbale fuerza tipo punta atornilla...
10,162470,i&o-headphones wireless akz-01 de la marca sm ...,¿Tienen audífonos inalámbricos con blultooth ...,"Sí, contamos con los audífonos inalámbricos AK...",audífono blultooth color conceto computadora
11,127423,"valvula esfera 1/2"" pegar duke de la marca sm ...",¿Tienen esa cosa que se pone en el tubo para a...,"Sí, contamos con la válvula esfera 1/2"" Pegar ...",cosa poner tubo abrir cerrar paso agua válvula...
12,128915,bestway sillon inflable color surtido 112 cm d...,¿Tienes un sillón que se pueda inflablar y des...,"Sí, contamos con el sillón inflable Bestway de...",tener sillón inflablar desinfllar playa lugar ...
13,14161,"pack x5 disco corte ac. 7""skil de la marca ski...",¿Tienen discos de corte de 7 pulgadas para amo...,"Sí, contamos con el pack de 5 discos de corte ...",disco corte herramienta
14,108973,atornillador 12v th-cd 12-2 li mp de la marca ...,"¿Tienen un taladro atornillador pequeño, sin c...","Sí, contamos con el atornillador Einhell TH-CD...",taladro cable quetenguir bateria durar tiempo ...
15,162315,roller cortable blackout gris 120x180 cm de la...,¿Tienen una cortina que se pueda subir y bajar...,"Sí, contamos con el roller blackout 120x180 cm...",cortina subir bajar bloquear luz graduar
16,26275,fotomural friendship 2 paños de la marca decop...,¿Tienen algún fotomural decorativo en varios p...,"Sí, contamos con el fotomural Friendship de 2 ...",fotomural paño colocar pared
17,142226,xiaomi tv 50 pulgadas uhd p1 l50m6 mtk de la m...,¿Tienen un televisor de 50 pulgadas con resolu...,"Sí, contamos con el Xiaomi TV de 50"", resoluci...",televisor resolución k sistema android acceso ...
18,133453,taladro de banco 32mm 2hp de la marca kaili de...,¿Tienen un taladro de banco potente que tenga ...,"Sí, contamos con el taladro de banco Kaili de ...",taladro banco mesa chuck
19,138403,bateria 40b19l(35ah/330a) de la marca bosch de...,¿Tienen una batería de auto de 35 amperios-hor...,"Sí, contamos con la batería Bosch 40B19L de 35...",batería auto amperios-hora ofrecer desempeño a...
20,61243,bloq.de humedad y salitre 1gl de la marca maje...,¿Tienen algún producto para cubrir superficies...,"Sí, contamos con el bloqueador de humedad y sa...",producto cubrir superficie humedad salitre par...
21,133058,trampa multiposicion para lavatorio y lavadero...,¿Tienen una trampa multiposición para lavatori...,"Sí, contamos con la trampa multiposición Cofle...",multiposición lavatorio lavadero instalar
22,96733,"espatula flexible 5"" de la marca stanley del a...",¿Tienen una espátula flexible para trabajos de...,"Sí, contamos con la espátula flexible de 5"" St...",espátula trabajo pintura drywall
23,120115,caja chica roja con llave de la marca werken d...,¿Tienen una caja de seguridad pequeña con llav...,"Sí, contamos con la caja de seguridad Werken C...",caja seguridad llave guardar dinero objeto valor
24,22245,plywood moldaje b/cp 9mm 1.22x2.44m de la marc...,¿Tienen triplay fenólico de 9 mm que sea resis...,"Sí, contamos con el triplay fenólico Moldeja B...",triplay mm humedad apto estructura carpintería
25,144128,rl cable thw-90 450/750 v 12 awg blanco 5m de ...,¿Cuál es la diferencia entre el cable THW-90 y...,El cable THW-90 es ideal para instalaciones fi...,diferencia cable tipo cable instalación
26,157026,piso cementicio grey cenizo 120x60 2.16m2 de l...,¿Cómo se comporta el piso cementicio en áreas ...,El piso cementicio Grey Cenizo es excepcionalm...,comportar piso cementicio área tráfico
27,134222,pulverizador 2lt de la marca ferticorp del are...,¿El pulverizador ferticorp es apto para desinf...,"Sí, nuestro pulverizador puede realizar un roc...",ferticorp desinfectar superficie
28,121599,prd est trama mix beige 30x60 ext 1.63 de la m...,¿La placa celima es adecuada para revestir par...,"Sí, la placa Trama Mix Beige es ideal para rev...",placa celima revestir pared mantener
29,134749,piscina estructural circular 15232lt - 427x122...,¿La piscina circular es fácil de instalar y se...,"Sí, la piscina estructural circular es fácil d...",piscina circular instalar patio
30,149697,"letrero peligro alto voltaje, 30 x 40 cm de la...",¿Los letreros de seguridad son adecuados para ...,"Sí, este letrero de peligro alto voltaje es ve...",letrero seguridad instalación exteriores
31,133344,desarmador con accesorios 29pcs de la marca ka...,¿Los desarmadores kamasa son versátil y adecua...,"Sí, este desarmador es ideal para apretar y af...",desarmador kamasa trabajo precisión
32,143455,organizador sobre inodoro haya de la marca tuh...,¿El organizador de inodoro es funcional y resi...,"Sí, este organizador es muy funcional y está d...",organizador inodoro baño
33,151771,vanitorio brescia caramelo de la marca bianely...,¿Qué cuidados debo tener con los vanitorios pa...,Para mantener su vanitorio Brescia en excelent...,cuidado vanitorio asegurar durabilidad
34,161680,taper 1.2l con cubiertos de la marca sm del ar...,¿El taper de cubiertos es adecuado para llevar...,"Sí, este taper de 1.2 litros es ideal para lle...",taper cubierto comida característica
35,117298,fiddler audifono con microfono azul de la marc...,¿Los audífonos fiddler son compatibles con mis...,¡Absolutamente! Los audífonos Fiddler con micr...,audífono fiddler dispositivo calidad sonido ca...
36,82863,zocalo porcelanato esmaltado line stone 7.3x60...,¿El zócalo de porcelanato es adecuado para pro...,"Sí, el zócalo porcelanato esmaltado Line Stone...",zócalo porcelanato proteger pared ambiente trá...
37,118259,papelera magaly #20 metalizada de la marca rey...,¿La papelera metalizada es para uso en la coci...,¡Por supuesto! La papelera Magaly está diseñad...,papelera cocina asegurar yo mantener
38,14455,batería s560dh (60ah/460a) de la marca bosch d...,¿Qué precauciones debo tener al instalar la ba...,"Al instalar la batería S560DH, es crucial empe...",precaución instalar batería bosh automóvil
39,151492,command gancho ancla niquel satinado decorativ...,¿El gancho ancla de niquel es fácil de instala...,"Sí, se adhiere firmemente sin dañar la pared y...",gancho anclar niquel instalar casa
40,158994,lámpara led ballena de la marca orange del are...,¿La lámpara ballena es adecuada para la habita...,"Sí, la lámpara LED Ballena es perfecta para ha...",ballena habitación niño
41,151737,"disco multicorte 180x1.6x22.23 7""x1/16""x7/8"" d...",¿El disco multicorte norton es versátil y pued...,"Sí, este disco multicorte es ideal para cortar...",disco norton cortar tipo material
42,162041,kit tal dhp485z dtd153z 2bat carg mp de...,¿El kit de taladro makita es adecuado para tra...,"Sí, este kit Makita es perfecto para trabajos ...",kit taladro trabajo incluir
43,153140,pegamentos chemita gris extrafuerte x 25 kg de...,¿El pegamento chemita sirve para enchapar en a...,"Sí, el pegamento Chemita es ideal para enchapa...",servir enchapar ambiente exteriores
44,147622,colgante montefio plata de la marca eglo del ...,¿la luz colgante es adecuado para iluminar gra...,"Sí, el colgante Montefio es perfecto para ilum...",luz iluminar espacio diseño

In [35]:
def ner_rag(query):
    retrieved = retrieve(query, k=3)
    context = "\n\n".join(retrieved)
    print(context)
    return context

ner_rag('papelera pedal preferencia color')

papelera black mate 4lt con pedal caída lenta de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 27.00 cm, ancho del producto 23.00 cm, profundidad del producto 27.00 cm, volumen del producto 16767, ean 2000001618783, medidas 23.00x27.00x27.00, tipo de producto baño, modelo pp0463na-wd, color negro, material polipropileno, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . .

papelera redonda negro 5 lt con pedal cierre lento de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 30.00 cm, ancho del producto 23.00 cm, profundidad del producto 23.00 cm, volumen del producto 15870, ean 2000001618851, medidas 23.00x23.00x30.00, tipo de producto baño, modelo bir0090ba-wd, color negro, material acero, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . .

papelera redond metal con pedal 3 lt negro de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 24.50 cm, ancho del producto 20.00 cm, profundidad del producto 20.00 cm, volumen del producto 9800, ean 2000001618868, medidas 20.00x20.00x24.50, tipo de producto baño, modelo ir0041ab-wd, color negro, material acero, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . .

'papelera black mate 4lt con pedal caída lenta de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 27.00 cm, ancho del producto 23.00 cm, profundidad del producto 27.00 cm, volumen del producto 16767, ean 2000001618783, medidas 23.00x27.00x27.00, tipo de producto baño, modelo pp0463na-wd, color negro, material polipropileno, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . . \n\npapelera redonda negro 5 lt con pedal cierre lento de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 30.00 cm, ancho del producto 23.00 cm, profundidad del producto 23.00 cm, volumen del producto 15870, ean 2000001618851, medidas 23.00x23.00x30.00, tipo de producto baño, modelo bir0090ba-wd, color negro, material acero, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . . \n\npapelera redond metal con pedal 3 lt negro de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 24.50 cm, ancho del producto 20.00 cm, profundidad del producto 20.00 cm, volumen del producto 9800, ean 2000001618868, medidas 20.00x20.00x24.50, tipo de producto baño, modelo ir0041ab-wd, color negro, material acero, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . . '

In [31]:
ner_rag('limpiar piso')

papelera rino 120 lt de la marca basa del area de limpieza para los herramientas de limpieza general de la linea tachos de procedencia nacional. volumen del producto 0, ean 7753688003964, color no aplica, garantía 1 año, procedencia nacional. . . .

limpiador piso madera y lam 700 ml de la marca binner del area de limpieza para los limpiadores y desinfectantes de la linea limpiadores y protectores de piso de procedencia nacional. altura del producto 29.00 cm, ancho del producto 11.50 cm, profundidad del producto 5.00 cm, volumen del producto 1667.5, ean 7702155030378, medidas 11.50x5.00x29.00, tipo de producto limpiador, modelo piso madera y laminado, color verde, material otros, garantía 1 año, procedencia nacional, país de origen colombia. Limpia, cuida y luce unos pisos renovados con el limpiador para pisos de madera, ideal para tu hogar.. Limpieza profunda.. . Usar la cantidad indicada.

papelera bodeguita 35 lt residuos peligrosos de la marca basa del area de limpieza para los herramientas de limpieza general de la linea tachos de procedencia nacional. volumen del producto 0, ean 7755206016807, color no aplica, garantía 1 año, procedencia nacional. . . .

In [32]:
ner_rag('lampara mesa foco')

lámpara de mesa negro e27 h26cm kanel de la marca inspire del area de iluminacion para los iluminacion decorativa de la linea lamparas de mesa de procedencia importado. altura del producto 26.50 cm, ancho del producto 23.00 cm, profundidad del producto 23.00 cm, volumen del producto 14018.5, ean 3276007274400, medidas 23.00x23.00x26.50, tipo de producto lámpara, modelo kanel, color negro, material metal, garantía 1 año, procedencia importado, país de origen china. Complementa la iluminación de tus espacios con la lámpara de mesa que hará que tu sala sea mucho más acogedora.. Excelente iluminación. Diseño moderno.. . Colocar sobre superficies planas.

lampara de mesa e14 akora de la marca inspire del area de iluminacion para los iluminacion decorativa de la linea lamparas de mesa de procedencia importado. altura del producto 17.20 cm, ancho del producto 11.50 cm, profundidad del producto 11.50 cm, volumen del producto 2274.7, diametro del producto 0, ean 3276007575767, medidas 11.50x11.50x17.20, tipo de producto lámpara, modelo akora, material madera/tela, garantía 5 años, procedencia importado, país de origen china. pIlumina tus espacios con la elegante Lámpara de Mesa Inspire Akora. Esta lámpara de mesa de la marca Inspire, modelo Akora, destaca por su excelente iluminación y su resistencia. Con un diseño en madera y tela, esta lámpara de mesa es perfecta para colocar sobre superficies planas. Con dimensiones de 11.5 cm de ancho y profundidad, y 17.2 cm de altura, esta lámpara es ideal para crear ambientes acogedores y luminosos en tu hogar. Características de la Lámpara de Mesa Inspire Akora:ul liDiseño elegante en madera y tela. liExcelente iluminación para tus espacios. liResistente y duradera. liDimensiones: 11.5 cm de ancho y profundidad, 17.2 cm de altura./ul. Excelente iluminación. Resistencia y durabilidad.. No aplica. Colocar sobre superficies planas.

lampara de mesa class cromo y tela de la marca sul del area de iluminacion para los iluminacion decorativa de la linea lamparas de mesa de procedencia nacional. volumen del producto 0, ean 8426107107824, color no aplica, garantía 1 año, procedencia nacional. . . .

In [33]:
ner_rag('chapa b calidad abrir cerrar puerta ventana casa')

casaca ventilada 10.8-18v l sin bat/carg/adap de la marca makita del area de herramientas para los herramientas electricas inalambricas de la linea herramientas multipropositos inal de procedencia nacional. volumen del producto 0, ean 88381864107, tipo de producto casaca, garantía 1 año, procedencia nacional. Diseñada especialmente para trabajos en ambientes calurosos o húmedos. Tejido lavable, se puede lavar en lavadora.. . No incluye batería.. Leer las instrucciones de uso, antes de emplear el producto.

gancho para quitar cabello d lavatorio de la marca galo del area de gasfiteria para los accesorios sanitarios de la linea accesorios sanitarios de procedencia nacional. volumen del producto 0, ean 7707321340282, tipo de producto accesorio, modelo quita cabello, color no aplica, garantía 1 año, procedencia nacional. Simplemente inserta el agarrador, empuja el mango y tira suavemente hacia afuera para quitar las obstrucciones.. . .

puerta blanca contraplacada palace 40x75x2.07 de la marca dimfer del area de ferreteria para los puertas de interior de la linea mdf o hdf de procedencia nacional. acabado pre acabado, altura del producto 207.00 cm, ancho del producto 75.00 cm, profundidad del producto 4.00 cm, volumen del producto 62100, ean 7754140000897, medidas 75.00x4.00x207.00, tipo de producto puerta, modelo palace, color blanco, material madera/mdf, garantía 5 años, procedencia nacional, país de origen perú. La puerta es perfecta para tus proyectos debido a que se puede combinar con una amplia variedad de marcos, ventanas u otros elementos dentro de un mismo espacio. Ideal para dividir habitaciones u otros espacios de los pasillos de la casa. Está fabricada con pino radiata HDF, lo cual hace de esta puerta una estructura liviana pero sólida.. Puertas contra placadas HDF con bastidores de pino radiata y base primer, soporte para cerradura de perilla. Ideal para espacios de interior. Bastidor de pino. Cuenta con un relleno Honey Comb. Diseño de bajo relieve por ambas caras. Estabilidad gracias a su estructura compuesta de madera pino libre de tensiones.. Pre pintada blanca. No es recomendable para zonas exteriores.. Para la instalación adquirir marco, kit de instalación y bisagras.  Medir correctamente el área del vano a utilizar para evitar problemas en la instalación. Ambientar la puerta a la humedad y temperatura del lugar donde se instalará, 72 horas antes.  Colocar en forma horizontal una osbre otra aislada del piso. Antes de pintar, limpie y realice un suave lijado.  Debe ser pintada en los 6 lados, en un plazo no mayor a 48 horas de haber sido instalada. Dar mantenimiento anualmente.

In [36]:

dp['CONTEXTO'] = dp['NER'].apply(ner_rag)
dp

papelera black mate 4lt con pedal caída lenta de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 27.00 cm, ancho del producto 23.00 cm, profundidad del producto 27.00 cm, volumen del producto 16767, ean 2000001618783, medidas 23.00x27.00x27.00, tipo de producto baño, modelo pp0463na-wd, color negro, material polipropileno, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . .

papelera redonda negro 5 lt con pedal cierre lento de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 30.00 cm, ancho del producto 23.00 cm, profundidad del producto 23.00 cm, volumen del producto 15870, ean 2000001618851, medidas 23.00x23.00x30.00, tipo de producto baño, modelo bir0090ba-wd, color negro, material acero, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . .

papelera redond metal con pedal 3 lt negro de la marca orange del area de baños para los organizacion de baño de la linea tachos de procedencia importado. acabado mate, altura del producto 24.50 cm, ancho del producto 20.00 cm, profundidad del producto 20.00 cm, volumen del producto 9800, ean 2000001618868, medidas 20.00x20.00x24.50, tipo de producto baño, modelo ir0041ab-wd, color negro, material acero, garantía 1 año, procedencia importado, país de origen china. Promart trae para ti la papelera con diseño compacto que te ayudará a almacenar los desperdicios.. . .
papelera rino 120 lt de la marca basa del area de limpieza para los herramientas de limpieza general de la linea tachos de procedencia nacional. volumen del producto 0, ean 7753688003964, color no aplica, garantía 1 año, procedencia nacional. . . .

limpiador piso madera y lam 700 ml de la marca binner del area de limpieza para los limpiadores y desinfectantes de la linea limpiadores y protectores de piso de procedencia nacional. altura del producto 29.00 cm, ancho del producto 11.50 cm, profundidad del producto 5.00 cm, volumen del producto 1667.5, ean 7702155030378, medidas 11.50x5.00x29.00, tipo de producto limpiador, modelo piso madera y laminado, color verde, material otros, garantía 1 año, procedencia nacional, país de origen colombia. Limpia, cuida y luce unos pisos renovados con el limpiador para pisos de madera, ideal para tu hogar.. Limpieza profunda.. . Usar la cantidad indicada.

papelera bodeguita 35 lt residuos peligrosos de la marca basa del area de limpieza para los herramientas de limpieza general de la linea tachos de procedencia nacional. volumen del producto 0, ean 7755206016807, color no aplica, garantía 1 año, procedencia nacional. . . .
lámpara de mesa negro e27 h26cm kanel de la marca inspire del area de iluminacion para los iluminacion decorativa de la linea lamparas de mesa de procedencia importado. altura del producto 26.50 cm, ancho del producto 23.00 cm, profundidad del producto 23.00 cm, volumen del producto 14018.5, ean 3276007274400, medidas 23.00x23.00x26.50, tipo de producto lámpara, modelo kanel, color negro, material metal, garantía 1 año, procedencia importado, país de origen china. Complementa la iluminación de tus espacios con la lámpara de mesa que hará que tu sala sea mucho más acogedora.. Excelente iluminación. Diseño moderno.. . Colocar sobre superficies planas.

lampara de mesa e14 akora de la marca inspire del area de iluminacion para los iluminacion decorativa de la linea lamparas de mesa de procedencia importado. altura del producto 17.20 cm, ancho del producto 11.50 cm, profundidad del producto 11.50 cm, volumen del producto 2274.7, diametro del producto 0, ean 3276007575767, medidas 11.50x11.50x17.20, tipo de producto lámpara, modelo akora, material madera/tela, garantía 5 años, procedencia importado, país de origen china. pIlumina tus espacios con la elegante Lámpara de Mesa Inspire Akora. Esta lámpara de mesa de la marca Inspire, modelo Akora, destaca por su excelente iluminación y su resistencia. Con un diseño en madera y tela, esta lámpara de mesa es perfecta para colocar sobre superficies planas. Con dimensiones de 11.5 cm de ancho y profundidad, y 17.2 cm de altura, esta lámpara es ideal para crear ambientes acogedores y luminosos en tu hogar. Características de la Lámpara de Mesa Inspire Akora:ul liDiseño elegante en madera y tela. liExcelente iluminación para tus espacios. liResistente y duradera. liDimensiones: 11.5 cm de ancho y profundidad, 17.2 cm de altura./ul. Excelente iluminación. Resistencia y durabilidad.. No aplica. Colocar sobre superficies planas.

lampara de mesa class cromo y tela de la marca sul del area de iluminacion para los iluminacion decorativa de la linea lamparas de mesa de procedencia nacional. volumen del producto 0, ean 8426107107824, color no aplica, garantía 1 año, procedencia nacional. . . .
llave de rueda para camion 32 x 33mm de la marca tramontina del area de herramientas para los herramientas de mano de la linea llaves de procedencia nacional. volumen del producto 0, ean 7891114045956, tipo de producto llave, color no aplica, garantía 1 año, procedencia nacional. . . .

llave de rueda para camion 27 x 33mm de la marca tramontina del area de herramientas para los herramientas de mano de la linea llaves de procedencia nacional. volumen del producto 0, ean 7891114045970, tipo de producto llave, color no aplica, garantía 1 año, procedencia nacional. . . .

llave dchavainsa classic palanca sin sal cr de la marca vainsa del area de baños para los griferia de baño de la linea llave ducha de procedencia nacional. volumen del producto 0, ean 7756513162805, tipo de producto llave, modelo classic, garantía 1 año, procedencia nacional. La llave de ducha cuenta con un diseño moderno y elegante que destacará dentro de la decoración de tu baño.. . . Maniobrar con cuidado para evitar el deterioro de las llave y salida de ducha, limpiar con un paño seco, en caso de acumulación de sarro limpiar con vinagre blanco y agua tibia, para mantener el brillo del cromado no limpiar con material abrasivo.
papelera rino 120 lt de la marca basa del area de limpieza para los herramientas de limpieza general de la linea tachos de procedencia nacional. volumen del producto 0, ean 7753688003964, color no aplica, garantía 1 año, procedencia nacional. . . .

limpiador off quitagrasa naranja 500 ml de la marca easy del area de limpieza para los limpiadores y desinfectantes de la linea desinfectantes y desatoradores de procedencia nacional. volumen del producto 0, ean 7702626201566, color no aplica, garantía 1 año, procedencia nacional. . . .

papelera bodeguita 35 lt papel y carton de la marca basa del area de limpieza para los herramientas de limpieza general de la linea tachos de procedencia nacional. volumen del producto 0, ean 7755206016791, color no aplica, garantía 1 año, procedencia nacional. . . .
luz guia led 3w, 30°k ip65 de la marca luminika del area de iluminacion para los focos de la linea bulbo leds de procedencia nacional. altura del producto 8.50 cm, ancho del producto 8.50 cm, profundidad del producto 4.10 cm, volumen del producto 296.225, ean 2000001304648, medidas 8.50x4.10x8.50, tipo de producto led, modelo luz guía, color blanco, garantía 1 año, procedencia nacional. Foco LED que consume muy poca energía en comparación de los focos ahorradores y convencionales, ayudando al medio ambiente y a tu economía.. Encendido instantáneo. Libre de mercurio. Baja emisión de calor. Protección medio ambiente.. . Ideal para oficinas, centros comerciales, salas de conferencias, corredores, pasillos.

luz guia led 1w con on-off luz calida de la marca lightech del area de iluminacion para los focos de la linea focos especiales de procedencia nacional. altura del producto 7.50 cm, ancho del producto 6.50 cm, profundidad del producto 2.00 cm, volumen del producto 97.5, ean 7750902089629, medidas 6.50x2.00x7.50, tipo de producto luz, modelo c/on-off luz calida, color blanco, material pvc, garantía 1 año, procedencia nacional, país de origen perú. Un LED guía es perfecto para movilizarse en la noche por lugares donde hay poca luz. Ideal para pasillos, corredores oscuros, caminos al aire libre, entre otros.. Luz guía tipo led, cuenta con enchufe e interruptor incorporado, diseño pequeño y decorativo.. Ideal para diferentes tipos de ambiente como dormitorio, pasadizos, escaleras, etc.. Tener en cuenta que este tipo de luminaria no se le puede dimar.

foco led gu10 8w luz calida de la marca lightech del area de iluminacion para los focos de la linea dicroicos de procedencia nacional. altura del producto 5.50 cm, volumen del producto 0, diametro del producto 5.00 cm, ean 7750902107439, tipo de producto foco, modelo dicroíco, color blanco, material pvc, garantía 1 año, procedencia nacional, país de origen perú. Obtén en Promart este hermoso Foco LED de luz cálida le da a tus ambientes un aspecto más hogareño y confortante. Los focos LED están diseñados para que ahorres una gran cantidad de energía y durar más.. Foco en forma de copa, diseño con ingreso GU10, sistema de bajo consumo y de mejor iluminación, ademas no genera altas temperaturas, libre de mercurio y es ecológico.. Luminaria con 90% de ahorro de energía, comparado con una lámpara incandescente. Tener en cuenta que este tipo de luminaria no se le puede dimar.
casaca ventilada 10.8-18v l sin bat/carg/adap de la marca makita del area de herramientas para los herramientas electricas inalambricas de la linea herramientas multipropositos inal de procedencia nacional. volumen del producto 0, ean 88381864107, tipo de producto casaca, garantía 1 año, procedencia nacional. Diseñada especialmente para trabajos en ambientes calurosos o húmedos. Tejido lavable, se puede lavar en lavadora.. . No incluye batería.. Leer las instrucciones de uso, antes de emplear el producto.

gancho para quitar cabello d lavatorio de la marca galo del area de gasfiteria para los accesorios sanitarios de la linea accesorios sanitarios de procedencia nacional. volumen del producto 0, ean 7707321340282, tipo de producto accesorio, modelo quita cabello, color no aplica, garantía 1 año, procedencia nacional. Simplemente inserta el agarrador, empuja el mango y tira suavemente hacia afuera para quitar las obstrucciones.. . .

puerta blanca contraplacada palace 40x75x2.07 de la marca dimfer del area de ferreteria para los puertas de interior de la linea mdf o hdf de procedencia nacional. acabado pre acabado, altura del producto 207.00 cm, ancho del producto 75.00 cm, profundidad del producto 4.00 cm, volumen del producto 62100, ean 7754140000897, medidas 75.00x4.00x207.00, tipo de producto puerta, modelo palace, color blanco, material madera/mdf, garantía 5 años, procedencia nacional, país de origen perú. La puerta es perfecta para tus proyectos debido a que se puede combinar con una amplia variedad de marcos, ventanas u otros elementos dentro de un mismo espacio. Ideal para dividir habitaciones u otros espacios de los pasillos de la casa. Está fabricada con pino radiata HDF, lo cual hace de esta puerta una estructura liviana pero sólida.. Puertas contra placadas HDF con bastidores de pino radiata y base primer, soporte para cerradura de perilla. Ideal para espacios de interior. Bastidor de pino. Cuenta con un relleno Honey Comb. Diseño de bajo relieve por ambas caras. Estabilidad gracias a su estructura compuesta de madera pino libre de tensiones.. Pre pintada blanca. No es recomendable para zonas exteriores.. Para la instalación adquirir marco, kit de instalación y bisagras.  Medir correctamente el área del vano a utilizar para evitar problemas en la instalación. Ambientar la puerta a la humedad y temperatura del lugar donde se instalará, 72 horas antes.  Colocar en forma horizontal una osbre otra aislada del piso. Antes de pintar, limpie y realice un suave lijado.  Debe ser pintada en los 6 lados, en un plazo no mayor a 48 horas de haber sido instalada. Dar mantenimiento anualmente.
i&o-maceta color turquesa solido deco lavanda de la marca orange del area de tendencias para los colecciones de la linea decoracion de procedencia importado. altura del producto 12.00 cm, volumen del producto 0, diametro del producto 14.00 cm, ean 2000001291337, tipo de producto maceta, modelo deco lavanda, color no aplica, material terracota, garantía 5 años, procedencia importado, país de origen china. . Ideal para la decoración conteniendo plantas y/o flores. Diseño de color sólido.. . Mantener limpio y seco, para evitar la acumulación de polvo y gérmenes.

i&o-maceta color rosado solido deco lavanda de la marca orange del area de tendencias para los colecciones de la linea decoracion de procedencia importado. altura del producto 12.00 cm, volumen del producto 0, diametro del producto 14.00 cm, ean 2000001291467, tipo de producto maceta, modelo deco lavanda, color rosa, material terracota, garantía 5 años, procedencia importado, país de origen china. . Ideal para la decoración conteniendo plantas y/o flores. Diseño de color sólido.. . Mantener limpio y seco, para evitar la acumulación de polvo y gérmenes.

flor salvaje morada en maceta - 18 cm de la marca orange del area de jardin para los deco jardin de la linea plantas artificiales de procedencia importado. altura del producto 18.00 cm, ancho del producto 15.00 cm, profundidad del producto 15.00 cm, volumen del producto 4050, ean 3015120000004, medidas 15.00x15.00x18.00, tipo de producto planta, modelo flor salvaje, color morado, material plástico, garantía por defecto de fabricación, procedencia importado, país de origen china. Dale color y vida a tus ambientes con los distintos modelos de plantas artificiales que tenemos para ti. Ideales para interiores y exteriores. Busca la que se adecúe más al estilo de tu decoración.. Para decorar ambientes. Fácil de limpiar y mantener.. Conservar en ambientes interiores para su correcta conservación.. Limpiar periódicamente para evitar que se adhieran sustancias no deseadas al producto. A la hora de limpieza primero se debe quitar el polvo con un plumero, luego enjuagar con agua y finalmente limpiar con un paño seco
set de terraza tavarua 6 personas de la marca reyplast del area de aire libre y temporada para los terrazas de la linea muebles de terraza de procedencia nacional. volumen del producto 0, ean 7750062015278, tipo de producto terraza, modelo tavarua, color marrón, material polipropileno, garantía 1 año, procedencia nacional, país de origen chile. Un espacio pequeño no es impedimento para tener una terraza. Este set de terraza es ideal para ahorrar espacio y seguir disfrutando del verano. ¡Disfruta este verano con Promart.pe!. Resistente para mantenerlo en ambientes abieros como jardines o piscinas.. . No limpiar con producto abrasivos ni corrosivos.

set de terraza tavarua 4 personas de la marca reyplast del area de aire libre y temporada para los terrazas de la linea muebles de terraza de procedencia nacional. volumen del producto 0, ean 7750062015124, tipo de producto terraza, modelo tavarua, color marrón, material polipropileno, garantía 1 año, procedencia nacional, país de origen chile. Disfruta a gusto de tu terraza o jardín con el elegante set de terraza Tavarúa para 4 personas, elaborado con fibra sintética. ¡Lúcete con este set de muebles gracias a Promart!. Resistente para mantenerlo en ambientes abieros como jardines o piscinas.. . No limpiar con producto abrasivos ni corrosivos.

set de terraza tavarua 2 personas de la marca reyplast del area de aire libre y temporada para los terrazas de la linea muebles de terraza de procedencia nacional. volumen del producto 0, ean 7750062015261, tipo de producto terraza, color no aplica, garantía 1 año, procedencia nacional. Un espacio pequeño no es impedimento para tener una terraza. Este juego de terraza Tavarua es ideal para ahorrar espacio y seguir disfrutando del verano. . .
lenovo audifono ht18 negro de la marca lenovo del area de electricidad para los tecnologia de la linea audifonos y mini speakers de procedencia nacional. altura del producto 7.00 cm, ancho del producto 4.00 cm, profundidad del producto 2.00 cm, volumen del producto 56, diametro del producto 0, ean 2000001521502, medidas 4.00x2.00x7.00, tipo de producto audífono, modelo ht18, color negro, material plástico, garantía 06 meses por defectos de fabricación, procedencia nacional, país de origen china. Versión Bluetooth 5.0. Diseño: True Wireless. Puertos de carga tipo C. Duración de batería hasta 4 h. Disfruta de lo más nuevo que Promart.pe trae para ti.. Versión Bluetooth 5.0. Diseño: True Wireless. Puertos de carga tipo C. Duración de batería hasta 4 h.. No aplica. Almacenar en un lugar ventilado.

parlante bluetooth 8w radio fm 2116 luces de la marca prolink del area de electricidad para los tecnologia de la linea electronica  de procedencia importado. altura del producto 9.70 cm, ancho del producto 19.60 cm, profundidad del producto 10.30 cm, volumen del producto 1958.236, ean 793969305209, medidas 19.60x10.30x9.70, tipo de producto parlante, modelo radio fm 2116 luces, color negro, material abs, garantía 1 año, procedencia importado, país de origen china. . Versión de Bluetooth: 5.3+EDR. Potencia: 8Wx2. Batería: 1800 mAh. Tiempo de reproducción: 3-4 horas (depende del uso individual). Tiempo de carga: 3-4 horas. Función: BT, USB, AUX, Micro SD, Radio FM, Luces LED (8 modos de iluminación para opciones). .

lecoo parlante bluetooth portatil ds152 de la marca lecoo del area de electricidad para los tecnologia de la linea electronica  de procedencia nacional. altura del producto 17.80 cm, ancho del producto 35.60 cm, profundidad del producto 13.40 cm, volumen del producto 8491.312, ean 6971859345595, medidas 35.60x13.40x17.80, tipo de producto parlante, modelo ds152, color negro, material plástico, garantía 06 meses por defectos de fabricación, procedencia nacional. Con el parlante podrás disfrutar de un excelente karaoke en casa y muchas horas de música.. Tipo Boombox. Con Bluetooth. IPX5. Radio FM. Puerto USB. Tiempo de reproducción 4.5 h. Luces RGB. 18 W RMS.. . Ubicar sobre superficies planas. Apagar mientras no esté en uso.
audif inalamb bluetooth tws negros mixduo de la marca maxell del area de electricidad para los tecnologia de la linea audifonos y mini speakers de procedencia nacional. altura del producto 20.00 cm, ancho del producto 7.00 cm, profundidad del producto 4.00 cm, volumen del producto 560, ean 25215505669, medidas 7.00x4.00x20.00, tipo de producto audífono, modelo no aplica, color negro, material pvc, garantía 1 mes, procedencia nacional, país de origen perú. Disfruta de tus canciones favoritas con este moderno audífono.. . .

i&o-caja almacenadora plegable osos aire nórdico de la marca orange del area de tendencias para los colecciones de la linea decoracion de procedencia importado. altura del producto 25.00 cm, ancho del producto 25.00 cm, profundidad del producto 25.00 cm, volumen del producto 15625, ean 2000001159071, medidas 25.00x25.00x25.00, tipo de producto caja, modelo aire nórdico, color gris, material notex, garantía 1 año, procedencia importado, país de origen china. Disfrutemos el otoño en nuestra casa con la tendencia Aire Nórdico que Promart trae para ti.Los colores nórdicos son muy suaves y dan mucha calma y tranquilidad a los ambientes.. . .


,SKU,CHUNK,Pregunta,Respuesta,NER,CONTEXTO
0,19812,papelera buzon 10 con pedal de la marca durap...,Necesito una papelera con pedal de preferencia...,Tenemos papelera buzon 10 con pedal duraplast.,papelera pedal preferencia color,papelera black mate 4lt con pedal caída lenta ...
1,149655,piso tec atenas mrfl r.sma 45x45 2.23m2 de la ...,como puedo limpiar un piso ceramico?,Se recomienda limpiar con un paño humedecido.,limpiar piso,papelera rino 120 lt de la marca basa del area...
2,153567,lámpara de mesa solo2 1x40w de la marca eglo d...,"tengo una lampara de mesa, que foco utiliza?",cualquier bombilla con castillo E27.,lampara mesa foco,lámpara de mesa negro e27 h26cm kanel de la ma...
3,149436,locker plastico abs lp102 llave doblepin verd ...,busco un casillero con llave,Tenemos un locker plastico abs.,casillero llave,llave de rueda para camion 32 x 33mm de la mar...
4,126558,lirio blanco - 91 cm de la marca orange del ar...,como puedo limpiar mis flores artificailes?,"Primero quita el polvo con un plumero, luego e...",limpiar flor,papelera rino 120 lt de la marca basa del area...
5,33021,reflector portatil x 500w de la marca total de...,¿Tienen un focos o luces portátil para exteri...,"Sí, contamos con un reflector portátil de 500W...",foco luz exteriores funcionir,"luz guia led 3w, 30°k ip65 de la marca luminik..."
6,146725,cierrapuerta modelo 3005 de la marca yale del ...,¿Tienen chapa con las tres b de bueno bonito ...,"Sí, contamos con el cierrapuertas Yale modelo ...",chapa b calidad abrir cerrar puerta ventana casa,casaca ventilada 10.8-18v l sin bat/carg/adap ...
7,152300,ramo de peonias rosas de la marca atmosphera d...,¿Tienes esos ramos de flores de plastico o f...,"Sí, contamos con el ramo de peonías rosas Atmo...",tener ramo flor plastico flor color decorar ca...,i&o-maceta color turquesa solido deco lavanda ...
8,158016,silla zero gravedad metal textileno gris silve...,¿Tienes una silla de playa que se reclinable o...,"Sí, contamos con la silla Zero Gravedad de met...",tener silla playa pese usar él terraza playa r...,set de terraza tavarua 6 personas de la marca ...
9,145793,atornillador gsr 18v-60fc 2bat de la marca bos...,¿necesito un atornillador que no tenga cbale e...,"Sí, contamos con el atornillador Bosch GSR 18V...",atornillador cbale fuerza tipo punta atornilla...,lenovo audifono ht18 negro de la marca lenovo ...
10,162470,i&o-headphones wireless akz-01 de la marca sm ...,¿Tienen audífonos inalámbricos con blultooth ...,"Sí, contamos con los audífonos inalámbricos AK...",audífono blultooth color conceto computadora,audif inalamb bluetooth tws negros mixduo de l...
11,127423,"valvula esfera 1/2"" pegar duke de la marca sm ...",¿Tienen esa cosa que se pone en el tubo para a...,"Sí, contamos con la válvula esfera 1/2"" Pegar ...",cosa poner tubo abrir cerrar paso agua válvula...,"válvula d paso 1"" pvc sin rosca de la marca pa..."
12,128915,bestway sillon inflable color surtido 112 cm d...,¿Tienes un sillón que se pueda inflablar y des...,"Sí, contamos con el sillón inflable Bestway de...",tener sillón inflablar desinfllar playa lugar ...,sillon puff - gabo - negro de la marca deco ho...
13,14161,"pack x5 disco corte ac. 7""skil de la marca ski...",¿Tienen discos de corte de 7 pulgadas para amo...,"Sí, contamos con el pack de 5 discos de corte ...",disco corte herramienta,"disco diamantado 14"" de la marca dewalt del ar..."
14,108973,atornillador 12v th-cd 12-2 li mp de la marca ...,"¿Tienen un taladro atornillador pequeño, sin c...","Sí, contamos con el atornillador Einhell TH-CD...",taladro cable quetenguir bateria durar tiempo ...,cable robacorriente 400amp 2.5mts de la marca ...
15,162315,roller cortable blackout gris 120x180 cm de la...,¿Tienen una cortina que se pueda subir y bajar...,"Sí, contamos con el roller blackout 120x180 cm...",cortina subir bajar bloquear luz graduar,cortina peva rayitas celestes de la marca pitu...
16,26275,fotomural friendship 2 paños de la marca decop...,¿Tienen algún fotomural decorativo en varios p...,"Sí, contamos con el fotomural Friendship de 2 ...",fotomural paño colocar pared,fotomural on top 8 paños de la marca decopapel...
17,142226,xiaomi tv 50 pulgadas uhd p1 l50m6 mtk de la m...,¿Tienen un televisor de 50 pulgadas con resolu...,"Sí, contamos con el Xiaomi TV de 50"", resoluci...",televisor resolución k sistema android acceso ...,xiaomi tv 50 pulgadas uhd p1 l50m6 mtk de la m...
18,133453,taladro de banco 32mm 2hp de la marca kaili de...,¿Tienen un taladro de banco potente que tenga ...,"Sí, contamos con el taladro de banco Kaili de ...",taladro banco mesa chuck,taladro de banco 20mm 1.5hp de la marca kaili ...
19,138403,bateria 40b19l(35ah/330a) de la marca bosch de...,¿Tienen una batería de auto de 35 amperios-hor...,"Sí, contamos con la batería Bosch 40B19L de 35...",batería auto amperios-hora ofrecer desempeño a...,bateria 12v l3- 780 ss de la marca etna del ar...
20,61243,bloq.de humedad y salitre 1gl de la marca maje...,¿Tienen algún producto para cubrir superficies...,"Sí, contamos con el bloqueador de humedad y sa...",producto cubrir superficie humedad salitre par...,bloq.de humedad y salitre 1gl de la marca maje...
21,133058,trampa multiposicion para lavatorio y lavadero...,¿Tienen una trampa multiposición para lavatori...,"Sí, contamos con la trampa multiposición Cofle...",multiposición lavatorio lavadero instalar,desagüe para lavatorio push con s reb pp de la...
22,96733,"espatula flexible 5"" de la marca stanley del a...",¿Tienen una espátula flexible para trabajos de...,"Sí, contamos con la espátula flexible de 5"" St...",espátula trabajo pintura drywall,pintura para drywall mayor a 20 m2 de la marca...
23,120115,caja chica roja con llave de la marca werken d...,¿Tienen una caja de seguridad pequeña con llav...,"Sí, contamos con la caja de seguridad Werken C...",caja seguridad llave guardar dinero objeto valor,chapa escritorio de la marca global trader del...
24,22245,plywood moldaje b/cp 9mm 1.22x2.44m de la marc...,¿Tienen triplay fenólico de 9 mm que sea resis...,"Sí, contamos con el triplay fenólico Moldeja B...",triplay mm humedad apto estructura carpintería,carpa para 6 ottawa vi de la marca national ge...
25,144128,rl cable thw-90 450/750 v 12 awg blanco 5m de ...,¿Cuál es la diferencia entre el cable THW-90 y...,El cable THW-90 es ideal para instalaciones fi...,diferencia cable tipo cable instalación,cable trenzado usb-c a usb-c - 2m negro de la ...
26,157026,piso cementicio grey cenizo 120x60 2.16m2 de l...,¿Cómo se comporta el piso cementicio en áreas ...,El piso cementicio Grey Cenizo es excepcionalm...,comportar piso cementicio área tráfico,piso cementicio natural gris 61x61cm 1.48m2 de...
27,134222,pulverizador 2lt de la marca ferticorp del are...,¿El pulverizador ferticorp es apto para desinf...,"Sí, nuestro pulverizador puede realizar un roc...",ferticorp desinfectar superficie,pulverizador 2lt de la marca ferticorp del are...
28,121599,prd est trama mix beige 30x60 ext 1.63 de la m...,¿La placa celima es adecuada para revestir par...,"Sí, la placa Trama Mix Beige es ideal para rev...",placa celima revestir pared mantener,destornillador punta plana 8.0x150mm de la ma...
29,134749,piscina estructural circular 15232lt - 427x122...,¿La piscina circular es fácil de instalar y se...,"Sí, la piscina estructural circular es fácil d...",piscina circular instalar patio,piscina inflable armado rapido 9677lt - 457x84...
30,149697,"letrero peligro alto voltaje, 30 x 40 cm de la...",¿Los letreros de seguridad son adecuados para ...,"Sí, este letrero de peligro alto voltaje es ve...",letrero seguridad instalación exteriores,instalaciones rheem-bryant de la marca sm del ...
31,133344,desarmador con accesorios 29pcs de la marca ka...,¿Los desarmadores kamasa son versátil y adecua...,"Sí, este desarmador es ideal para apretar y af...",desarmador kamasa trabajo precisión,broca madera 6 mm de la marca bosch del area d...
32,143455,organizador sobre inodoro haya de la marca tuh...,¿El organizador de inodoro es funcional y resi...,"Sí, este organizador es muy funcional y está d...",organizador inodoro baño,organizador sin inodoro lima bl de la marca bi...
33,151771,vanitorio brescia caramelo de la marca bianely...,¿Qué cuidados debo tener con los vanitorios pa...,Para mantener su vanitorio Brescia en excelent...,cuidado vanitorio asegurar durabilidad,vanitorio madrid miel de la marca tuhome del a...
34,161680,taper 1.2l con cubiertos de la marca sm del ar...,¿El taper de cubiertos es adecuado para llevar...,"Sí, este taper de 1.2 litros es ideal para lle...",taper cubierto comida característica,taper 1.2l con cubiertos de la marca sm del ar...
35,117298,fiddler audifono con microfono azul de la marc...,¿Los audífonos fiddler son compatibles con mis...,¡Absolutamente! Los audífonos Fiddler con micr...,audífono fiddler dispositivo calidad sonido ca...,"audífono in ear, micrófono, boton para contest..."
36,82863,zocalo porcelanato esmaltado line stone 7.3x60...,¿El zócalo de porcelanato es adecuado para pro...,"Sí, el zócalo porcelanato esmaltado Line Stone...",zócalo porcelanato proteger pared ambiente trá...,ambientador smart scent car 52gr centralsul de...
37,118259,papelera magaly #20 metalizada de la marca rey...,¿La papelera metalizada es para uso en la coci...,¡Por supuesto! La papelera Magaly está diseñad...,papelera cocina asegurar yo mantener,papelera automatica n.1-crema de la marca basa...
38,14455,batería s560dh (60ah/460a) de la marca bosch d...,¿Qué precauciones debo tener al instalar la ba...,"Al instalar la batería S560DH, es crucial empe...",precaución instalar batería bosh automóvil,bateria 65b24l (52ah/480a) de la marca bosch d...
39,151492,command gancho ancla niquel satinado decorativ...,¿El gancho ancla de niquel es fácil de instala...,"Sí, se adhiere firmemente sin dañar la pared y...",gancho anclar niquel instalar casa,perchero haya 3 ganchos blanco reloj de la mar...
40,158994,lámpara led ballena de la marca orange del are...,¿La lámpara ballena es adecuada para la habita...,"Sí, la lámpara LED Ballena es perfecta para ha...",ballena habitación niño,sheflera m de la marca sm del area de jardin p...
41,151737,"disco multicorte 180x1.6x22.23 7""x1/16""x7/8"" d...",¿El disco multicorte norton es versátil y pued...,"Sí, este disco multicorte es ideal para cortar...",disco norton cortar tipo material,disco abrasiv corte metal 180mm de la marca de...
42,162041,kit tal dhp485z dtd153z 2bat carg mp de...,¿El kit de taladro makita es adecuado para tra...,"Sí, este kit Makita es perfecto para trabajos ...",kit taladro trabajo incluir,kit trabajador (lentes y guantes tapones) de...
43,153140,pegamentos chemita gris extrafuerte x 25 kg de...,¿El pegamento chemita sirve para enchapar en a...,"Sí, el pegamento Chemita es ideal para enchapa...",servir enchapar ambiente exteriores,ambientador smart scent car 52gr centralsul de...
44,147622,colgante montefio plata de la marca eglo del ...,¿la luz colgante es adecuado para iluminar gra...,"Sí, el colgante Montefio es perfecto para ilum...",luz iluminar espacio diseño,lampara colgante larissa 1 luz de la marca egl...